language: rust

matrix:
  fast_finish: true

rust:
  - nightly
  - beta
  - stable

sudo: false

notifications:
  email: false

env:
  global:
    # override the default '--features unstable' used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - secure "e3552e9e91c59695f4e24bac4a4fe50fa1eb4422"

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - travis-cargo --only stable doc

after_success:
 - travis-cargo --only stable doc-upload
 - travis-cargo coveralls --no-sudo --verify

