sudo: false
language: rust
rust:
- stable
- nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test
after_success:
- |
  travis-cargo --only stable doc-upload &&
  travis-cargo coveralls --no-sudo --verify
os:
- windows
- linux
- osx
env:
  global:
  - secure: Atdu6xhV4TdcgUUYOOKIsWavKUx9kG+bYC9OpiO0F573eawpWXUYUlz36qLWXGRyyj77cHO41hAv0ZGBAMIc/Ctn6ZWEgnhmEzGt2hySg3EqLpv3m3k8SLN9Vg+/xZ/V1a4dipfudw6KBDIOnew2fZ0f+hGSHd1EMEjFiPrm3zJ/BGjjS6WwlIWYPmH6gg9Ix4y7qXpv5VdqYg51wMAmWJYyta+a7lGbk9QJFp4Ud1Chz9w8/vsnbwIbNzA68twnU9X4FH923lAZqopyXwFJlZ0KRrbsxGMlrkfkD9kMorbhYH0jyP1xrM/4cSRe9dW69qkRRQtR0qCdvwkg3xkyMcbRPJLJlptsbBqu5qXcO0QETFhfDNbGehN/rmhC0BtfGvhw4EQHsymQNaEyXQlVFGXuUyg4uwz/p0KvHu7C9scc0cYJUzpBUQoIQMdaMbXGGLK9sXBWZxV4E9uC4JEnP8oWnYan6ZCI9YAzqhXwlZLFMM73TWODZqOJm3+0x8ryk9oUEcfr2OWf3aN25pDeXN7z0m0vsIjkutQhPm75ilf5Rz4Tgzb0lv6tyMOf560Om+Xf681NW0wfTvHSmgzoWxOlNPT4JTqIMZ1isaLjobUZNINTnIP8GHvF0inNLsh1o4YjsmF3VTuDIYbJLBWDR4/ENIrOnbxIkFuco4x8kdQ=
