language: rust

rust:
  - nightly
  - beta
  - stable

sudo: false

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email: false

env:
  global:
    -TRAVIS_CARGO_NIGHTLY_FEATURE=dev
    - secure: JXzzQvpYSdwSoJd0nUSJlMCfzSzQJCDXiA9C81hIw9AccZT2MJrTDXVrJDc5fU9r6GbRHs0Xw0p9VNHk/O4Jrys8man7TmzCSS9FsfX/Sdof9qLMBOurFlBc+kUV+sWgXIXdYpGBVp7IiTZKWM43E6kQnVTsm5Lf4a3F8N7fXdSeNNfyZF1fbsmqhIdU+5uojyXHRDREnksQrCzuiFvym8ctrURLDwt0KPCr5uVsFuo6W63FGCFKlj5Ipa1cnYVqgHdS36D0w+kmEqib6yS/KWH+Sf/ku+cMzlmlq4/dcgsshMH3wkCjdxHBbVvLzCzD6VxaMHlAQ4X1s+HUhLVPW2eLSgZEh1yUsH1JG397qRIuHvvLYGlDJJfu6ah0xWT3EJl13XVQdPzQfdAYYmJhFoBrrPRaN9fXjilyC0PeMwet/85B9m675agNjXz7MPlinNOCmfKkofPgzBqO1F6h1wmKArlpd24NuwkGlD5Kl9sXS5f8p0TNIbY8Ha3rrJ0C6cpLaiVzOoNqjW1v9ovaPJto+9aiTqKI4Cyh2giaH2dz/UTxmmx2eWeQ8XgT2QhJSs8MX5L5Zzeof9dCASpblRMD9pSM6GgRn4tFFKSzPGBpCN5VcbotU8k9OXg+2vgQ4sYAIxXVlUQ4SfBGJnFMyl/ZVsiyeqnkRINbVfV0VBU=

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script: |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES

after_success:
  # upload rust doc on the gh-pages
  - travis-cargo --only stable doc-upload
  - env COVERAGE_TESTING=1 travis-cargo coveralls --no-sudo

