language: rust

matrix:
  fast_finish: true
  include:
    - rust: nightly
      env: FEATURES="--features nightly"
    - rust: beta
    - rust: stable
    - rust: stable
      env: FEATURES="--no-default-features"

script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --no-run; fi'

sudo: false

notifications:
  email: false

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success: |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
  cmake .. &&
  make &&
  make install DESTDIR=../tmp  &&
  cd ../.. &&
  ls target/debug &&
  ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/notion-*
