[package]
name = "notion"
version = "0.1.0"
authors = ["Zypeh <Zypeh.geek@gmail.com>"]

[lib]
name = "notion"
path = "lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "notion"
path = "main.rs"

[dependencies]
